### ISSUE TITLE
Error on linux

### ISSUE THREAD

**Issue by StefanMeier13** [Helioviewer-Project/JHelioviewer#169]
java.lang.UnsupportedClassVersionError: org/helioviewer/jhv/viewmodel/view/jp2view/kakadu/JHV_KduException : Unsupported major.minor version 52.0
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
       at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
       at java.lang.Class.getDeclaredMethods0(Native Method)
       at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
       at java.lang.Class.getDeclaredMethod(Class.java:2007)
       at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
       at com.install4j.runtime.launcher.UnixLauncher.main(Unknown Source)

**Comment by deiruch** [comment]
No longer occurs with new deployment.
