### ISSUE TITLE
Error 404 trying to load http://jhelioviewer.org/updateJHV.txt 

### ISSUE THREAD

**Issue by PabloIAS** [Helioviewer-Project/JHelioviewer#177]
Hello, 

When I launch jhelioviewer I have an error in the log 
It is not a big deal but annoying for end users that may think that there is a problem.

Extract of the log  : 
2015-03-25 18:03:20,037 [JHV Update Checker] ERROR root - Error retrieving update server
java.io.IOException: Error opening http connection to http://jhelioviewer.org/updateJHV.txt Response code: 404
	at org.heliov

iewer.base.DownloadStream.connect(DownloadStream.java:124)
	at org.helioviewer.base.DownloadStream.getInput(DownloadStream.java:169)
	at org.helioviewer.jhv.JHVUpdate.run(JHVUpdate.java:107)
	at java.lang.Thread.run(Thread.java:745)

Test done with 2.3.0 rev 503 

Regards, 
Pablo 
IAS

**Comment by deiruch** [comment]
This issue no longer occurs with the latest version.
