### ISSUE TITLE
Error MAC platform 

### ISSUE THREAD

**Issue by PabloIAS** [Helioviewer-Project/JHelioviewer#178]
Hello, 

Our users have reported an error launching jhelioviewer with java 1.8 on MAC 
We have tested and reproduced the error  (on Maverick with the last java 1.8) 
NB : 
Our end user needs java 1.8 for an application that embebs jhelioviewer 

Here the log : 
java -jar "/Applications/JHelioviewer.apContents/Resources/Java/JHelioviewer.jar" -jhv "[startTime=2012-02-08T00:00:00Z;endTime=2012-02-08T01:01:26Z;linked=true;cadence=60;imageScale=500;imageLayers=[SDO,AIA,AIA,171,1,100]]"
JavaHelioviewerLauncher > Detected Java version: 1.8
JavaHelioviewerLauncher > Initialize settings and read argmuents for JVM
JavaHelioviewerLauncher > Start JHelioviewer with the following java virtual machine parameters:-cp /Applications/JHelioviewer.app/Contents/Resources/Java/JHelioviewer_IAS.jar:/Applications/JHelioviewer.app/Contents/Resources/Java/JHelioviewer_IAS.jar -Djava.library.path=/Users/lbeigbeder/JHelioviewer/Libs:/Users/lbeigbeder/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:. -Djava.ext.dirs="" "-Xmx1024m" "-Dapple.laf.useScreenMenuBar=true"
JavaHelioviewerLauncher > Start JHelioviewer with the following command-line options: "-jhv" "[startTime=2012-02-08T00:00:00Z;endTime=2012-02-08T01:01:26Z;linked=true;cadence=60;imageScale=500;imageLayers=[SDO,AIA,AIA,171,1,100]]"
2015-03-24 11:30:40,868 [main] INFO  root - JHelioviewer started with command-line options: -jhv [startTime=2012-02-08T00:00:00Z;endTime=2012-02-08T01:01:26Z;linked=true;cadence=60;imageScale=500;imageLayers=[SDO,AIA,AIA,171,1,100]]
2015-03-24 11:30:40,869 [main] INFO  root - Create directories...
2015-03-24 11:30:40,871 [main] INFO  root - >> JHVGlobals.determineVersionAndRevision() > Look for jar file: /Applications/JHelioviewer.app/Contents/Resources/Java/JHelioviewer_IAS.jar
2015-03-24 11:30:40,872 [main] INFO  root - Initializing JHelioviewer
2015-03-24 11:30:41,181 [main] INFO  root - Load settings
2015-03-24 11:30:41,189 [main] INFO  root - OS: mac - arch: x86-64 - java arch: 64
2015-03-24 11:30:41,195 [main] INFO  root - Try to load Kakadu libraries
2015-03-24 11:30:41,200 [main] INFO  root - Connect to file:/Users/lbeigbeder/JHelioviewer/Libs/kakadu.xml
2015-03-24 11:30:41,201 [main] INFO  root - Connect to http://jhelioviewer.org/libjhv/kakadu.xml
2015-03-24 11:30:43,036 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.arch not satisfied. Current value: x86-64
2015-03-24 11:30:43,037 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:43,037 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:43,037 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:43,037 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:43,037 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:43,037 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:43,037 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:43,037 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:43,037 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.java.arch not satisfied. Current value: 64
2015-03-24 11:30:43,038 [main] INFO  root - Connect to file:/Users/lbeigbeder/JHelioviewer/Libs/libkdu_jni-mac-x86-64.jnilib
2015-03-24 11:30:43,073 [main] INFO  root - Successfully loaded Kakadu libraries
2015-03-24 11:30:43,075 [main] INFO  root - Use cache directory: /Users/lbeigbeder/JHelioviewer/Cache/
2015-03-24 11:30:43,081 [main] INFO  root - Update settings
2015-03-24 11:30:43,086 [AWT-EventQueue-0] INFO  root - Try to load OpenGL libraries
2015-03-24 11:30:43,086 [AWT-EventQueue-0] INFO  root - Connect to file:/Users/lbeigbeder/JHelioviewer/Libs/jogl.xml
2015-03-24 11:30:43,087 [AWT-EventQueue-0] INFO  root - Connect to http://jhelioviewer.org/libjhv/jogl.xml
2015-03-24 11:30:43,495 [AWT-EventQueue-0] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:43,495 [AWT-EventQueue-0] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:43,496 [AWT-EventQueue-0] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:43,496 [AWT-EventQueue-0] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:43,496 [AWT-EventQueue-0] INFO  root - Connect to file:/Users/lbeigbeder/JHelioviewer/Libs/libgluegen-rt-mac.jnilib
2015-03-24 11:30:43,498 [AWT-EventQueue-0] INFO  root - Connect to file:/Users/lbeigbeder/JHelioviewer/Libs/libjogl-mac.jnilib
2015-03-24 11:30:43,512 [AWT-EventQueue-0] INFO  root - Connect to file:/Users/lbeigbeder/JHelioviewer/Libs/libjogl_awt-mac.jnilib
2015-03-24 11:30:43,522 [AWT-EventQueue-0] INFO  root - Successfully loaded OpenGL libraries
2015-03-24 11:30:43,522 [main] INFO  root - Try to install CG Compiler
2015-03-24 11:30:43,522 [main] INFO  root - Connect to file:/Users/lbeigbeder/JHelioviewer/Libs/cgc.xml
2015-03-24 11:30:43,523 [main] INFO  root - Connect to http://jhelioviewer.org/libjhv/cgc.xml
2015-03-24 11:30:43,709 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:43,709 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:43,709 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:43,709 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:43,710 [main] INFO  root - Connect to file:/Users/lbeigbeder/JHelioviewer/Libs/cgc-mac
2015-03-24 11:30:43,754 [main] INFO  root - Successfully installed CG Compiler
2015-03-24 11:30:43,754 [main] INFO  root - Install FFmpeg
2015-03-24 11:30:43,754 [main] INFO  root - Connect to file:/Users/lbeigbeder/JHelioviewer/Libs/ffmpeg.xml
2015-03-24 11:30:43,755 [main] INFO  root - Connect to http://jhelioviewer.org/libjhv/ffmpeg.xml
2015-03-24 11:30:43,951 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.arch not satisfied. Current value: x86-64
2015-03-24 11:30:43,952 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.arch not satisfied. Current value: x86-64
2015-03-24 11:30:43,952 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:43,952 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:43,952 [main] INFO  root - Connect to file:/Users/lbeigbeder/JHelioviewer/Libs/ffmpeg-mac-x86-64
2015-03-24 11:30:43,980 [main] INFO  root - Successfully installed FFmpeg tool
2015-03-24 11:30:43,980 [main] INFO  root - Install MP4Box
2015-03-24 11:30:43,980 [main] INFO  root - Connect to file:/Users/lbeigbeder/JHelioviewer/Libs/mp4box.xml
2015-03-24 11:30:43,981 [main] INFO  root - Connect to http://jhelioviewer.org/libjhv/mp4box.xml
2015-03-24 11:30:44,168 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:44,169 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:44,169 [main] WARN  root - > ResourceLoader.requirementsNotSatisfied() >> Requirement jhv.os not satisfied. Current value: mac
2015-03-24 11:30:44,169 [main] INFO  root - Connect to file:/Users/lbeigbeder/JHelioviewer/Libs/mp4box-mac
2015-03-24 11:30:44,194 [main] INFO  root - Successfully installed MP4Box tool
2015-03-24 11:30:44,194 [main] INFO  root - Initialize GUI
2015-03-24 11:30:44,433 [ObservationSetup] INFO  root - Connect to http://helioviewer.ias.u-psud.fr/helioviewer/api/?action=getDataSources&verbose=true
2015-03-24 11:30:44,530 [ObservationSetup] INFO  root - Connect to http://helioviewer.ias.u-psud.fr/helioviewer/api/index.php?action=getJP2Image&observatory=SDO&instrument=AIA&detector=AIA&measurement=171&date=2015-03-24T10:30:44Z&json=true&jpip=true
2015-03-24 11:30:45,100 [JHV Update Checker] INFO  root - Connect to http://jhelioviewer.org/updateJHV.txt
2015-03-24 11:30:45,101 [main] INFO  root - Load plugin settings
2015-03-24 11:30:45,114 [main] INFO  root - Add internal plugin: FilterPlugin
2015-03-24 11:30:45,124 [main] INFO  root - Download default plugins
2015-03-24 11:30:45,124 [main] INFO  root - Connect to file:/Users/lbeigbeder/JHelioviewer/Plugins/sdo-cutout.xml
2015-03-24 11:30:45,125 [main] INFO  root - Connect to http://jhelioviewer.org/libjhv/sdo-cutout.xml
2015-03-24 11:30:45,288 [JHV Update Checker] ERROR root - >> DownloadStream.connect() > Error opening http connection to http://jhelioviewer.org/updateJHV.txt Response code: 404
2015-03-24 11:30:45,289 [JHV Update Checker] ERROR root - Error retrieving update server
java.io.IOException: Error opening http connection to http://jhelioviewer.org/updateJHV.txt Response code: 404
	at org.helioviewer.base.DownloadStream.connect(DownloadStream.java:124)
	at org.helioviewer.base.DownloadStream.getInput(DownloadStream.java:169)
	at org.helioviewer.jhv.JHVUpdate.run(JHVUpdate.java:105)
	at java.lang.Thread.run(Thread.java:745)
2015-03-24 11:30:45,510 [main] INFO  root - Connect to file:/Users/lbeigbeder/JHelioviewer/Plugins/SDOCutOutPlugin.jar
2015-03-24 11:30:45,511 [main] INFO  root - Successfully downloaded SDO-Cutout plugin.
2015-03-24 11:30:45,512 [main] INFO  root - Connect to file:/Users/lbeigbeder/JHelioviewer/Plugins/default-plugins.xml
2015-03-24 11:30:45,512 [main] INFO  root - Connect to http://jhelioviewer.org/libjhv/default-plugins.xml
2015-03-24 11:30:45,694 [main] INFO  root - Connect to file:/Users/lbeigbeder/JHelioviewer/Plugins/HEKPlugin.jar
2015-03-24 11:30:45,705 [main] INFO  root - Successfully downloaded default plugins.
2015-03-24 11:30:45,705 [main] INFO  root - Search for plugins in /Users/lbeigbeder/JHelioviewer/Plugins/
2015-03-24 11:30:45,706 [main] INFO  root - PluginManager is trying to load the plugin located at file:/Users/lbeigbeder/JHelioviewer/Plugins/HEKPlugin.jar
2015-03-24 11:30:45,706 [main] INFO  root - PluginManager: Load plugin class :org.helioviewer.jhv.plugins.hekplugin.HEKPlugin
2015-03-24 11:30:45,764 [main] INFO  root - PluginManager is trying to load the plugin located at file:/Users/lbeigbeder/JHelioviewer/Plugins/SDOCutOutPlugin.jar
2015-03-24 11:30:45,764 [main] INFO  root - PluginManager: Load plugin class :org.helioviewer.plugins.sdocutoutplugin.SDOCutOutPlugin
2015-03-24 11:30:45,771 [main] INFO  root - Start main window
2015-03-24 11:30:45,934 [Thread-0] FATAL root - Runtime exception
java.lang.NoClassDefFoundError: apple/awt/ComponentModel
	at com.sun.opengl.impl.JAWT_DrawingSurface.GetDrawingSurfaceInfo0(Native Method)
	at com.sun.opengl.impl.JAWT_DrawingSurface.GetDrawingSurfaceInfo(JAWT_DrawingSurface.java:56)
	at com.sun.opengl.impl.macosx.MacOSXOnscreenGLDrawable$1.run(MacOSXOnscreenGLDrawable.java:165)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.opengl.impl.macosx.MacOSXOnscreenGLDrawable.lockSurface(MacOSXOnscreenGLDrawable.java:163)
	at com.sun.opengl.impl.macosx.MacOSXOnscreenGLContext.makeCurrentImpl(MacOSXOnscreenGLContext.java:57)
	at com.sun.opengl.impl.GLContextImpl.makeCurrent(GLContextImpl.java:134)
	at com.sun.opengl.impl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:182)
	at javax.media.opengl.GLCanvas$DisplayOnEventDispatchThreadAction.run(GLCanvas.java:452)
	at sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(OGLRenderQueue.java:229)
Caused by: java.lang.ClassNotFoundException: apple.awt.ComponentModel
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
ERROR: exception in QueueFlusher:
ERROR: javax.media.opengl.GLException: Attempt to make the same context current twice on thread Thread[Java2D Queue Flusher,10,system]
ERROR: 	at com.sun.opengl.impl.GLContextLock.lock(GLContextLock.java:83)
ERROR: 	at com.sun.opengl.impl.GLContextImpl.makeCurrent(GLContextImpl.java:131)
ERROR: 	at com.sun.opengl.impl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:182)
ERROR: 	at javax.media.opengl.GLCanvas$DisplayOnEventDispatchThreadAction.run(GLCanvas.java:452)
ERROR: 	at sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(OGLRenderQueue.java:229)
2015-03-24 11:30:54,590 [ObservationSetup] ERROR root - >> APIRequestManager.getLatestImageDate() > Error while opening stream. Use current date as initial end date.
java.io.IOException: Error in the server communication:Timeout while communicating with the server:
connect timed out
	at org.helioviewer.jhv.io.APIRequestManager.loadImage(APIRequestManager.java:128)
	at org.helioviewer.jhv.io.APIRequestManager.getLatestImageDate(APIRequestManager.java:65)
	at org.helioviewer.jhv.gui.dialogs.observation.ImageDataPanel$TimeSelectionPanel.setupTime(ImageDataPanel.java:465)
	at org.helioviewer.jhv.gui.dialogs.observation.ImageDataPanel$1.run(ImageDataPanel.java:124)
	at java.lang.Thread.run(Thread.java:745)

**Comment by deiruch** [comment]
Java 1.8 is supported by the most recent beta version.

**Comment by PabloIAS** [comment]
Hello, 
I don't see dmg file for the most recent beta version : Beta 24

Regards, 
Pablo

**Comment by deiruch** [comment]
There is also support for Java 1.8 in the prior beta releases, for example 2.3.23. Can you test with that?

**Comment by PabloIAS** [comment]
Sure I will 
Thank you

**Comment by StefanMeier13** [comment]
Sorry, there was an error by the upload. Now is the current version for Mac OS X available.
