### ISSUE TITLE
ThreadDeath

### ISSUE THREAD

**Issue by StefanMeier13** [Helioviewer-Project/JHelioviewer#245]
Raygun report https://app.raygun.io/dashboard/d60m9k/errors/837792708 has more details about the error

**Comment by deiruch** [comment]
java.lang.NullPointerException
  	at org.helioviewer.jhv.gui.dialogs.InstrumentModel$1.run(InstrumentModel.java:48)
  	at java.lang.Thread.run(Unknown Source)
