### ISSUE TITLE
[AWT-EventQueue-0] FATAL root - Runtime exception

### ISSUE THREAD

**Issue by GitatHub** [Helioviewer-Project/JHelioviewer#300]
System:
Both Fedora 26 AND 27 x64 with
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

Errors output:
java -jar JHelioviewer.jar &
[1] 3245
[user@local bin]$ 2017-11-24 16:03:24,386 [main] INFO  root - JHelioviewer started with command-line options:
2017-11-24 16:03:24,437 [main] INFO  root - Store log settings to /home/user/JHelioviewer-SWHV/Settings/log4j.properties
2017-11-24 16:03:24,441 [main] INFO  root - Running JHV/SWHV-2.11.3.8731 (amd64 Linux 4.13.13-300.fc27.x86_64) Oracle Corporation JRE 1.8.0_151
2017-11-24 16:03:24,708 [AWT-EventQueue-0] FATAL root - Runtime exception
java.lang.ExceptionInInitializerError
	at org.helioviewer.jhv.JHelioviewer.lambda$main$0(JHelioviewer.java:91)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.awt.HeadlessException
	at sun.awt.HeadlessToolkit.createCustomCursor(HeadlessToolkit.java:251)
	at org.helioviewer.jhv.gui.UIGlobals.<init>(UIGlobals.java:59)
	at org.helioviewer.jhv.gui.UIGlobals.<clinit>(UIGlobals.java:28)
	... 15 more
2017-11-24 16:03:24,836 [AWT-EventQueue-0] FATAL root - Runtime exception
java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1758)
	at javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1833)
	at javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1696)
	at javax.swing.JOptionPane.getWindowForComponent(JOptionPane.java:1637)
	at javax.swing.JOptionPane.createDialog(JOptionPane.java:956)
	at javax.swing.JOptionPane.createDialog(JOptionPane.java:918)
	at org.helioviewer.jhv.JHVUncaughtExceptionHandler.showErrorDialog(JHVUncaughtExceptionHandler.java:118)
	at org.helioviewer.jhv.JHVUncaughtExceptionHandler.uncaughtException(JHVUncaughtExceptionHandler.java:171)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Exception: java.awt.HeadlessException thrown from the UncaughtExceptionHandler in thread "AWT-EventQueue-0"

**Comment by deiruch** [comment]
This issue appears to be in the wrong project. Please post bug reports for the SWHV version of JHelioviewer here: https://github.com/Helioviewer-Project/JHelioviewer-SWHV/issues

**Comment by GitatHub** [comment]
@deiruch 
This project also has, I guess, the similar erros:
after installing JHelioviewer_3_0_19_amd64.rpm and run with "jhelioviewer"
in the same system environments mentioned above, I got
--------------------------------------
/tmp/install4jError1724234160636823846.log
Exception:

java.lang.ThreadDeath
	at java.lang.Thread.stop(Thread.java:853)
	at org.helioviewer.jhv.base.JHVUncaughtExceptionHandler.uncaughtException(JHVUncaughtExceptionHandler.java:224)
	at org.helioviewer.jhv.base.JHVUncaughtExceptionHandler.lambda$0(JHVUncaughtExceptionHandler.java:183)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

System properties:

jnlp.jogamp.tmp.cache.root=jln3045977188188237001
java.runtime.name=OpenJDK Runtime Environment
exe4j.moduleName=/opt/JHelioviewer/bin/jhelioviewer
sun.boot.library.path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.x86_64/jre/lib/amd64
java.vm.version=25.151-b12
java.vm.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
path.separator=:
java.vm.name=OpenJDK 64-Bit Server VM
file.encoding.pkg=sun.io
user.country=US
sun.java.launcher=SUN_STANDARD
sun.os.patch.level=unknown
install4j.exeDir=/opt/JHelioviewer/bin/
java.vm.specification.name=Java Virtual Machine Specification
user.dir=/opt/JHelioviewer/bin
java.runtime.version=1.8.0_151-b12
java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
i4jv=0
java.endorsed.dirs=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.x86_64/jre/lib/endorsed
os.arch=amd64
java.io.tmpdir=/tmp
line.separator=

raygunTag=release
java.vm.specification.vendor=Oracle Corporation
os.name=Linux
apple.laf.useScreenMenuBar=true
jhvVersion=3.0.19
proxySet=false
sun.jnu.encoding=UTF-8
java.library.path=/opt/JHelioviewer/bin::/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
sun.awt.enableExtraMouseButtons=true
install4j.launcherId=296
java.specification.name=Java Platform API Specification
java.class.version=52.0
user.locale=en_US
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
os.version=4.13.11-200.fc26.x86_64
i4j.vpt=true
install4j.swt=false
user.home=/home/user
user.timezone=Asia/Shanghai
java.awt.printerjob=sun.print.PSPrinterJob
file.encoding=UTF-8
install4j.jvmDir=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.x86_64/jre
java.specification.version=1.8
java.class.path=/opt/JHelioviewer/.install4j/i4jruntime.jar:/opt/JHelioviewer/classes:/opt/JHelioviewer/lib/annotation-detector-3.0.4.jar:/opt/JHelioviewer/lib/annotations.jar:/opt/JHelioviewer/lib/applicationinsights-core-1.0.1.jar:/opt/JHelioviewer/lib/bzip2.jar:/opt/JHelioviewer/lib/commons-io-2.4.jar:/opt/JHelioviewer/lib/commons-lang3-3.3.2.jar:/opt/JHelioviewer/lib/commons-logging-1.2.jar:/opt/JHelioviewer/lib/core-2.1.0.jar:/opt/JHelioviewer/lib/fits.jar:/opt/JHelioviewer/lib/gluegen-rt.jar:/opt/JHelioviewer/lib/gluegen-rt-natives-linux-amd64.jar:/opt/JHelioviewer/lib/gson-2.2.4.jar:/opt/JHelioviewer/lib/guava-18.0.jar:/opt/JHelioviewer/lib/httpclient-4.3.5.jar:/opt/JHelioviewer/lib/httpcore-4.3.2.jar:/opt/JHelioviewer/lib/i4jruntime.jar:/opt/JHelioviewer/lib/jogl-all.jar:/opt/JHelioviewer/lib/jogl-all-natives-linux-amd64.jar:/opt/JHelioviewer/lib/jsamp-1.3.5_signed.jar:/opt/JHelioviewer/lib/json.jar:/opt/JHelioviewer/lib/jsr305.jar:/opt/JHelioviewer/lib/junrar-0.7.jar:/opt/JHelioviewer/lib/kdu.jar:/opt/JHelioviewer/lib/log4j-1.2.16.jar:/opt/JHelioviewer/lib/slf4j-api-1.7.7.jar:/opt/JHelioviewer/lib/slf4j-nop-1.7.7.jar:/opt/JHelioviewer/lib/xuggle-xuggler-5.4-linux.jar:/opt/JHelioviewer/resources
user.name=hu
java.vm.specification.version=1.8
sun.java.command=com.install4j.runtime.launcher.UnixLauncher launch 107131ae   org.helioviewer.jhv.JHelioviewer
java.home=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.x86_64/jre
sun.arch.data.model=64
user.language=en
java.specification.vendor=Oracle Corporation
awt.toolkit=sun.awt.X11.XToolkit
java.vm.info=mixed mode
java.version=1.8.0_151
java.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.x86_64/jre/lib/ext:/usr/java/packages/lib/ext
sun.boot.class.path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.x86_64/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.x86_64/jre/lib/rt.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.x86_64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.x86_64/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.x86_64/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.x86_64/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.x86_64/jre/lib/jfr.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.fc26.x86_64/jre/classes
install4j.appDir=/opt/JHelioviewer/
java.vendor=Oracle Corporation
file.separator=/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
sun.font.fontmanager=sun.awt.X11FontManager
sun.io.unicode.encoding=UnicodeLittle
sun.cpu.endian=little
install4j.systemLanguage=en
install4j.keepLog=true
sun.desktop=gnome
sun.cpu.isalist=

**Comment by GitatHub** [comment]
This issue happened to Oracle JRE too:

[INFO] logger started at Sun Nov 26 00:02:01 CST 2017
[INFO] executable name: /opt/JHelioviewer/bin/jhelioviewer
[INFO] install4j version: 6.1.5 (build 6349)
[INFO] Properties: 
-- listing properties --
java.runtime.name=Java(TM) SE Runtime Environment
exe4j.moduleName=/opt/JHelioviewer/bin/jhelioviewer
sun.boot.library.path=/usr/java/jre1.8.0_152/lib/amd64
java.vm.version=25.152-b16
java.vm.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
path.separator=:
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
file.encoding.pkg=sun.io
user.country=US
sun.java.launcher=SUN_STANDARD
sun.os.patch.level=unknown
java.vm.specification.name=Java Virtual Machine Specification
user.dir=/opt/JHelioviewer/bin
java.runtime.version=1.8.0_152-b16
java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
i4jv=0
java.endorsed.dirs=/usr/java/jre1.8.0_152/lib/endorsed
os.arch=amd64
java.io.tmpdir=/tmp
line.separator=

raygunTag=release
java.vm.specification.vendor=Oracle Corporation
os.name=Linux
apple.laf.useScreenMenuBar=true
jhvVersion=3.0.19
sun.jnu.encoding=UTF-8
java.library.path=/opt/JHelioviewer/bin::/usr/java/pack...
sun.awt.enableExtraMouseButtons=true
install4j.launcherId=296
java.specification.name=Java Platform API Specification
java.class.version=52.0
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
os.version=4.13.11-200.fc26.x86_64
install4j.swt=false
i4j.vpt=true
user.home=/home/user
user.timezone=Asia/Shanghai
java.awt.printerjob=sun.print.PSPrinterJob
java.specification.version=1.8
install4j.jvmDir=/usr/java/jre1.8.0_152
file.encoding=UTF-8
user.name=hu
java.class.path=/opt/JHelioviewer/.install4j/i4jrunti...
java.vm.specification.version=1.8
sun.arch.data.model=64
java.home=/usr/java/jre1.8.0_152
sun.java.command=com.install4j.runtime.launcher.UnixLa...
java.specification.vendor=Oracle Corporation
user.language=en
awt.toolkit=sun.awt.X11.XToolkit
java.vm.info=mixed mode
java.version=1.8.0_152
java.ext.dirs=/usr/java/jre1.8.0_152/lib/ext:/usr/j...
sun.boot.class.path=/usr/java/jre1.8.0_152/lib/resources....
java.vendor=Oracle Corporation
file.separator=/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
sun.cpu.endian=little
sun.io.unicode.encoding=UnicodeLittle
sun.font.fontmanager=sun.awt.X11FontManager
sun.desktop=gnome
sun.cpu.isalist=
[INFO] com.install4j.runtime.beans.actions.update.CheckForUpdateAction [ID 402]: Execute action
       Property variable: updateDescriptor
       Property showError: false
       Property rollbackSupported: false
       Property url: http://www.jhelioviewer.org/updates/beta/updates.xml
       Property connectionFailureScript: null
       Property requestHeaders: []
       Property acceptAllCertificates: false
       Property askForProxy: false
       Property connectTimeout: 5000
       Property readTimeout: 10000
       Download: http://www.jhelioviewer.org/updates/beta/updates.xml to /tmp/i4jupd2392800368980492097.xml; size: 1230 bytes
       Variable changed: updateDescriptor=com.install4j.runtime.installer.config.update.UpdateDescriptorImpl@5bfbf16f[class com.install4j.runtime.installer.config.update.UpdateDescriptorImpl]
       Execute action successful after 703 ms
[INFO] com.install4j.runtime.beans.actions.control.SetVariableAction [ID 403]: Execute action
       Property variableName: updateDescriptorEntry
       Property responseFileVariable: false
       Property onlyIfUndefined: false
       Property failIfNull: true
       Property rollbackSupported: false
       Property script: com.install4j.script.I4jScript_Internal_189
[ERROR] com.install4j.runtime.beans.actions.control.SetVariableAction [ID 403]: Execute action not successful after 2 ms
[INFO] Canceled
